# Generated by Django 2.1.3 on 2019-03-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs411_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Easy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.IntegerField(default=0)),
            ],
        ),
    ]
